"""PDF, CSV, and JSON report generation."""

from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.core.models import Finding
from app.core.session import AssessmentSession


class ReportGenerator:
    """Generates professional assessment outputs from normalized findings."""

    def __init__(self, session: AssessmentSession, company_name: str, app_version: str) -> None:
        self.session = session
        self.company_name = company_name
        self.app_version = app_version

    def generate_pdf(self, findings: list[Finding]) -> Path:
        output = self.session.report_dir / "assessment_report.pdf"
        doc = SimpleDocTemplate(str(output), pagesize=LETTER)
        styles = getSampleStyleSheet()
        story: list[object] = []

        story.append(Paragraph("Soun Al Hosn Assessment Runner", styles["Title"]))
        story.append(Paragraph("Basic Cybersecurity Assessment Report", styles["Heading2"]))
        story.append(Paragraph(f"Prepared by: {self.company_name}", styles["Normal"]))
        story.append(Paragraph(f"Client: {self.session.intake.client_name}", styles["Normal"]))
        story.append(Paragraph(f"Site: {self.session.intake.site}", styles["Normal"]))
        story.append(Paragraph(f"Operator: {self.session.intake.operator_name}", styles["Normal"]))
        story.append(Paragraph(f"Session: {self.session.session_id}", styles["Normal"]))
        story.append(Paragraph(f"Runner version: {self.app_version}", styles["Normal"]))
        story.append(Paragraph(f"Generated UTC: {datetime.now(timezone.utc).isoformat()}", styles["Normal"]))
        story.append(Spacer(1, 12))

        story.append(Paragraph("Scope Control", styles["Heading2"]))
        story.append(Paragraph(f"Authorized scope: {self.session.intake.authorized_scope}", styles["Normal"]))
        story.append(Paragraph(f"Scope notes: {self.session.intake.scope_notes}", styles["Normal"]))
        story.append(Paragraph("Mode: read-only. No remediation or exploitation performed.", styles["Normal"]))
        story.append(Spacer(1, 12))

        story.append(Paragraph("Priority Action List", styles["Heading2"]))
        if findings:
            table_data = [["Risk", "Severity", "Finding", "Owner", "Effort"]]
            for finding in findings[:12]:
                table_data.append(
                    [
                        str(finding.risk_score),
                        finding.severity,
                        finding.title,
                        finding.owner_role,
                        finding.effort,
                    ]
                )
            table = Table(table_data, repeatRows=1)
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F2937")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ]
                )
            )
            story.append(table)
        else:
            story.append(Paragraph("No open findings were generated by the MVP checks.", styles["Normal"]))

        story.append(Spacer(1, 12))
        story.append(Paragraph("Findings Detail", styles["Heading2"]))
        for finding in findings:
            story.append(Paragraph(f"{finding.finding_id}: {finding.title}", styles["Heading3"]))
            story.append(
                Paragraph(
                    f"Severity: {finding.severity} | Confidence: {finding.confidence}",
                    styles["Normal"],
                )
            )
            story.append(Paragraph(f"Asset: {finding.asset}", styles["Normal"]))
            story.append(Paragraph(f"Evidence: {finding.evidence_summary}", styles["Normal"]))
            story.append(Paragraph(f"Why it matters: {finding.why_it_matters}", styles["Normal"]))
            story.append(Paragraph(f"Business impact: {finding.likely_business_impact}", styles["Normal"]))
            story.append(Paragraph("Remediation: " + "; ".join(finding.remediation_steps), styles["Normal"]))
            story.append(Paragraph("Validation: " + "; ".join(finding.validation_steps), styles["Normal"]))
            story.append(Spacer(1, 8))

        doc.build(story)
        return output

    def generate_action_csv(self, findings: list[Finding]) -> Path:
        output = self.session.report_dir / "action_plan.csv"
        with output.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(
                handle,
                fieldnames=[
                    "finding_id",
                    "app_version",
                    "title",
                    "severity",
                    "risk_score",
                    "owner_role",
                    "effort",
                    "status",
                    "remediation_steps",
                    "validation_steps",
                ],
            )
            writer.writeheader()
            for finding in findings:
                writer.writerow(
                    {
                        "finding_id": finding.finding_id,
                        "app_version": self.app_version,
                        "title": finding.title,
                        "severity": finding.severity,
                        "risk_score": finding.risk_score,
                        "owner_role": finding.owner_role,
                        "effort": finding.effort,
                        "status": finding.status,
                        "remediation_steps": " | ".join(finding.remediation_steps),
                        "validation_steps": " | ".join(finding.validation_steps),
                    }
                )
        return output

    def generate_findings_json(self, findings: list[Finding]) -> Path:
        output = self.session.report_dir / "findings.json"
        output.write_text(
            json.dumps(
                {
                    "metadata": {
                        "app_version": self.app_version,
                        "session_id": self.session.session_id,
                        "client_name": self.session.intake.client_name,
                        "site": self.session.intake.site,
                        "generated_utc": datetime.now(timezone.utc).isoformat(),
                        "read_only": True,
                    },
                    "findings": [finding.to_dict() for finding in findings],
                },
                indent=2,
                sort_keys=True,
            ),
            encoding="utf-8",
        )
        return output
